# Generated by Django 3.2.25 on 2024-06-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20240620_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
