# Generated by Django 3.2.25 on 2024-07-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_user_is_2fa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_code_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
