# Generated by Django 3.2.25 on 2024-07-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_match_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_type',
            field=models.CharField(max_length=255),
        ),
    ]
