# Generated by Django 3.2.25 on 2024-07-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_alter_games_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='loser_score',
            field=models.IntegerField(default=0),
        ),
    ]
